Given is a nested tuple. Write a program to modify the item (44) of a list inside a following tuple to 444.

Given:      tuple1 = (11, 22, [33, 44, 55],66,77)

In [1]:
tuple1 = (11, 22, [33, 44, 55],66,77)
tuple1[2][1] = 444
print(tuple1)

(11, 22, [33, 444, 55], 66, 77)


Write a program to add two lists index-wise. Create a new list that contains the 0th index item from both the list, then the 1st index item, and so on till the last element. any leftover items will get added at the end of the new list.

Given:      list1 = ["M", "na", "i", "Ke"]           list2 = ["y", "me", "s", "lly"]

In [2]:
list1 = ["M", "na", "i", "Ke"] 
list2 = ["y", "me", "s", "lly"]
res = []
for i in range(len(list1)):
    res.append(list1[i] + list2[i])
print(res)

['My', 'name', 'is', 'Kelly']


Write a Python program to change Brad’s salary to 85000 in the following dictionary.

Given:      sample_dict = {‘emp1': {'name': 'Jhon', 'salary': 75000},

  		      'emp2': {'name': 'Emma', 'salary': 80000},

 			      'emp3': {'name': 'Brad', 'salary': 500}}

In [3]:
sample_dict = {'emp1': {'name': 'Jhon', 'salary': 75000},

            'emp2': {'name': 'Emma', 'salary': 80000},

               'emp3': {'name': 'Brad', 'salary': 500}}

sample_dict['emp3']['salary'] = 85000

print(sample_dict)

{'emp1': {'name': 'Jhon', 'salary': 75000}, 'emp2': {'name': 'Emma', 'salary': 80000}, 'emp3': {'name': 'Brad', 'salary': 85000}}


WAP to Return a set of elements present in Set A or B, but not both.

Given:           set1 = {10, 20, 30, 40, 50,60,70}                 set2 = {40, 50, 60, 70,80,90}

In [4]:
set1 = {10, 20, 30, 40, 50,60,70} 
set2 = {40, 50, 60, 70,80,90}
set1.symmetric_difference(set2)

{10, 20, 30, 80, 90}

WAP to Ask users to enter age, gender (M or F), marital status (Y or N) and then using following rules print their place of service.

If the employee is female, then she will work only in urban areas.

If employee is a male and age is in between 20 to 40 then he may work in anywhere

If the employee is male and age is between 40 to 60 then he will work in urban areas only.

And any other input of age should print "ERROR".

In [5]:
age = int(input('Enter Age:'))
gender = input('Enter gender, M or F:')
marital_status = input('Enter marital status, Y or N:')

if gender=='F':
    print('Will work in urban areas only')
elif gender=='M':
    if age>20 and age<40:
        print('May work anywhere')
    elif age>40 and age<60:
        print('Will work in urban areas only')
    else:
        print('ERROR')
else:
    print('ERROR')

Enter Age:25
Enter gender, M or F:M
Enter marital status, Y or N:Y
May work anywhere


In [6]:
# fibonacci
a = 0
b = 1
for i in range(0,10):
    print(a)
    a,b = b, a+b

0
1
1
2
3
5
8
13
21
34


In [24]:
# factorial of a number
factorial = 1
num = 3
for i in range(1,num+1):
    factorial = i* factorial
print(factorial)

6


Write a program to print the following number pattern using a for loop.

1

1 2

1 2 3

1 2 3 4

1 2 3 4 5

In [7]:
for i in range(1,6):
    for j in range(1,6):
        if j<=i:
            print(j,end = ' ')
    print('\n')

1 

1 2 

1 2 3 

1 2 3 4 

1 2 3 4 5 



Write a program to calculate the sum of series up to n term. For example, if n =5 the series will become 

        2 + 22 + 222 + 2222 + 22222 = 24690

In [8]:
def sum_series(num,n):
    sum1 = 0
    for i in range(1,n+1):
        sum1 = sum1 + int(str(num)*i) # to get the series convert into string and multiply
    return sum1

In [9]:
sum_series(2,5)

24690

In [10]:
sum_series(3,5)

37035

WAP to Find the element in a given list is “Even” or “ODD” using List Comprehension.

   List1= [12,23,34,45,56,67,78,89,90]

In [11]:
list1 = [12,23,34,45,56,67,78,89,90]
even  = [i for i in list1 if i%2==0]
odd   = [i for i in list1 if i%2!=0]
print('even:',even)
print('odd:',odd)

even: [12, 34, 56, 78, 90]
odd: [23, 45, 67, 89]


Write a program to create a function show_employee() using the following conditions.

It should accept the employee’s name, age and salary and display both.

If the salary is missing in the function call, then assign default value 9000 to salary.

In [12]:
def show_employee(name, age, salary=9000):
    return (f'Employee Name is {name}, employee age is {age} and employee salary is {salary}')

In [13]:
show_employee('Sam',25,27000)

'Employee Name is Sam, employee age is 25 and employee salary is 27000'

In [14]:
show_employee('Jack',27)

'Employee Name is Jack, employee age is 27 and employee salary is 9000'

Write a program to create a recursive function to calculate the sum of numbers between given two numbers.

In [15]:
def add_recursive(num1,num2):
    if num2==0:
        return num1
    else:
        return add_recursive(num1,num2-1)+1

In [16]:
add_recursive(100,120)

220

WAP to create an age list from the given DOB list using Lambda function.

               list1=[1991,1992,1994,1996,1998,2000,2001,2002,2004]

In [17]:
list1 = [1991,1992,1994,1996,1998,2000,2001,2002,2004]
age = map(lambda x:(2024-x), list1)
age_list = list(age)
age_list

[33, 32, 30, 28, 26, 24, 23, 22, 20]

Write a program to check if the given file is empty or not.

In [18]:
with open('file.txt','r') as data:
    data.read()
    pos = data.tell()
    if pos ==0:
        print('File is empty')
    else:
        print('File is not empty')

File is empty


WAP to Define a class attribute”color” with a default value white. I.e., Every Vehicle should be white.

Expected Output:

Color: White, Vehicle name: School Volvo, Speed: 180, Mileage: 12

Color: White, Vehicle name: Audi Q5, Speed: 240, Mileage: 18

In [19]:
class car():
    
    def __init__(self, name, speed, mileage, color = 'White'):
        self.color = color
        self.name = name
        self.speed = speed
        self.mileage = mileage
        
    def show_detail(self):
        print(f'Color: {self.color}, Vehicle name: {self.name}, Speed: {self.speed}, Mileage: {self.mileage}')

In [20]:
c1 = car('School Volvo','180','12')
c1.show_detail()

Color: White, Vehicle name: School Volvo, Speed: 180, Mileage: 12


In [21]:
c2 = car('Audi Q5','240','18')
c2.show_detail()

Color: White, Vehicle name: Audi Q5, Speed: 240, Mileage: 18


WAP to Create a 4X2 integer array and print the following Attributes: –

The shape of an array.

Array dimensions.

The Length of each element of the array in bytes.

In [22]:
import numpy as np

In [23]:
arr = np.arange(8).reshape(4,2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [24]:
print(arr.shape)

(4, 2)


In [25]:
arr.ndim

2

In [26]:
arr.itemsize

4

WAP to Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.



Expected Output:

Creating 8X3 array

[[10 11 12]

 [13 14 15]

 [16 17 18]

 [19 20 21]

 [22 23 24]

 [25 26 27]

 [28 29 30]

 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],[13, 14, 15]]), 

array([[16, 17, 18],[19, 20, 21]]), 

array([[22, 23, 24],[25, 26, 27]]), 

array([[28, 29, 30],[31, 32, 33]])]

In [27]:
arr1 = np.arange(10,34).reshape(8,3)

In [28]:
ans = np.array_split(arr1,4,axis=0)
ans

[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

WAP to create number series and apply the function, f(x) = x/2 on each and every element of the pandas series.

In [30]:
import pandas as pd
import numpy as np

In [31]:
ser = pd.Series(np.arange(10))
func = lambda x:x/2
ser.apply(func)

0    0.0
1    0.5
2    1.0
3    1.5
4    2.0
5    2.5
6    3.0
7    3.5
8    4.0
9    4.5
dtype: float64

WAP to convert given a dictionary into corresponding dataframe and display it.

dictionary = {'name': ['Vinay', 'Kushal', 'Aman'],

          	            'age' : [22, 25, 24],

          	            'occ' : ['engineer', 'doctor', 'accountant']}

In [32]:
data = {
    'name':['Vinay','Kushal','Aman'],
    'age':[22,25,24],
    'occ':['engineer','doctor','accountant']
}

In [33]:
df = pd.DataFrame(data)
df

name  age         occ
0   Vinay   22    engineer
1  Kushal   25      doctor
2    Aman   24  accountant

 Given is a dataframe showing Company Names (cname) and corresponding Profits (profit). WAP to convert the values of Profit column such that values in it greater than 0 are set to True and the rest are set to False.

                               cname                                             profit

0                           Shyam & Co.                                 -10000

1                           Ramlal & Bros.                                 10000

2                          Sharma Enterprises                    -5000

3                          Verma Furnitures                           15000

4                          Rahul Stores                                      20000

In [34]:
df = pd.DataFrame({
    'cname':['Shyam & Co.','Ramlal & Bros.','Sharma Enterprises','Verma Furnitures','Rahul Stores'],
    'profit':[-10000,10000,-5000,15000,20000]
})

In [35]:
df

cname  profit
0         Shyam & Co.  -10000
1      Ramlal & Bros.   10000
2  Sharma Enterprises   -5000
3    Verma Furnitures   15000
4        Rahul Stores   20000

In [36]:
func = lambda x:True if x>0 else False

In [37]:
df['profit'] = df['profit'].apply(func)

In [38]:
df

cname  profit
0         Shyam & Co.   False
1      Ramlal & Bros.    True
2  Sharma Enterprises   False
3    Verma Furnitures    True
4        Rahul Stores    True

WAP to generate the statistical summary of all the numerical features present in the given dataframe.

eid                         ename                 stipend               position

0    1                         Sid                       10000                employee

1    2                         Ramesh             10000               employee

2    3                        Ron                       5000                 intern

3    4                        Harry                   15000                senior_employee

In [39]:
df = pd.DataFrame({
    'eid':[1,2,3,4],
    'ename':['Sid','Ramesh','Ron','Harry'],
    'stipend':[10000,10000,5000,15000],
    'position':['employee','employee','intern','senior_employee']
})

In [40]:
df

eid   ename  stipend         position
0    1     Sid    10000         employee
1    2  Ramesh    10000         employee
2    3     Ron     5000           intern
3    4   Harry    15000  senior_employee

In [41]:
df['stipend'].describe()

count        4.000000
mean     10000.000000
std       4082.482905
min       5000.000000
25%       8750.000000
50%      10000.000000
75%      11250.000000
max      15000.000000
Name: stipend, dtype: float64